# -*- coding: utf-8 -*-
"""Contar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x1hLP4s4JiyAUjooFnNCgkLD3IZWtgFQ
"""

while(True):
  menu=str(input("""
  ==========BIENVENIDO A MI MENU===============
      a. Opcion Contar Consonantes sin vocales
      b. SALIR
  """))
  if(menu=="a"):
      def funcioncontsinvocal():
        palabra = input("Introduce una palabra: ").lower()

        vocales = "aeiou"

        contador = 0

        for letra in palabra:
            if letra.isalpha() and letra not in vocales:
              contador += 1

        print(f"\tLa cantidad de consonantes sin vocales en '{palabra}' es: {contador}")
      funcioncontsinvocal()
  elif(menu=="b"):
    break