# -*- coding: utf-8 -*-
"""Division2num.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AzrBEbqZgoJulAcxMgrETG0amz9iRXwD
"""

# Función recursiva para calcular la división de dos números

def FuncioRecurDiv(a,b):       #10,2
  if(a<b):                      # si a<b
    return 0                     # nos dará el valor de 0
  else:                              #sino procedera a hacer la siguiente ejecucación
    return(1 + FuncioRecurDiv(a-b,b))      #1+FRD(8,2)
                                             #1+FRD(6,2)
                                              #1+FRD(4,2)
                                               #1+FRD(2,2)
                                                 #1+FRD(0,2)
var_divi1=int(input("Ingrese un numero: "))                 # Para ingresar el valor de a
var_divi2=int(input("Ingrese un numero: "))                 # Para ingresar el valor de b
FuncioRecurDiv(var_divi1,var_divi2)