# -*- coding: utf-8 -*-
"""MasaCor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1it09SPm8YARUdzd5oDPLh0AFwdeZiOkS
"""

def funcioncalcularimc():
    peso = float(input("Introduce su peso (kg): "))
    talla = float(input("Introduce su talla (m): "))


    imc = peso / (talla ** 2)

    print(f"\tTu índice de masa corporal (IMC) es: {imc:.2f}")

    if imc < 18.5:
        print("\tBajo peso")
    elif 18.5 <= imc < 24.9:
        print("\tPeso normal")
    elif 25 <= imc < 29.9:
        print("\tSobrepeso")
    else:
        print("\tObesidad")

funcioncalcularimc()